pragma Singleton

import Quickshell
import QtQuick

Singleton {
    readonly property var hypridleStartCommand: ["systemctl", "--user", "start", "hypridle"]
    readonly property var hypridleStopCommand: ["systemctl", "--user", "stop", "hypridle"]
    readonly property var hypridleGetterCommand: ["systemctl", "--user", "is-active", "hypridle"]

    // Try to load Nix-generated overrides at runtime.
    // If MachineOverrides.qml exists (generated by the Nix module), use it.
    // If not (standalone mode), fall back to MachineDefaults.
    property var _overrides: null

    Component.onCompleted: {
        var comp = Qt.createComponent(Quickshell.shellDir + "/MachineOverrides.qml");
        if (comp.status === Component.Ready) {
            _overrides = comp.createObject(this);
        }
    }

    readonly property var current: _overrides || MachineDefaults
}
